export enum Action {
  'CREATE_RESTAURANT',
  'UPDATE_RESTAURANT',
  'DELETE_RESTAURANT',
  'CREATE_COMMENT',
  'UPDATE_COMMENT',
  'DELETE_COMMENT',
  'REPLY_COMMENT',
  'CREATE_REVIEW',
  'UPDATE_REVIEW',
  'DELETE_REVIEW',
  'REPLY_REVIEW',
  'UPDATE_USER',
  'DELETE_USER',
  'VIEW_USER'
}
